# Generated by Django 4.1.4 on 2023-01-10 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=7)),
                ('nome', models.CharField(max_length=120)),
                ('grupo', models.CharField(choices=[('1', 'Grupo I'), ('2', 'Grupo II'), ('3', 'Grupo III'), ('4', 'Grupo IV')], max_length=1)),
                ('setor', models.CharField(choices=[('sefit', 'SEFIT'), ('sevop', 'SEVOP'), ('selve', 'SELVE'), ('areas', 'AREA'), ('coesp', 'COESP'), ('gasup', 'GASUP'), ('geren', 'GERENCIA')], max_length=25)),
                ('x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_general.servidor')),
            ],
        ),
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posto_base', models.CharField(max_length=120)),
                ('roteiro', models.TextField(max_length=500)),
                ('data_registro', models.DateField(auto_now=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_general.servidor')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitacao', models.TextField(max_length=500)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('participantes', models.TextField(max_length=500)),
                ('data_registro', models.DateField(auto_now=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_general.servidor')),
            ],
        ),
        migrations.CreateModel(
            name='Fds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('posto_base', models.CharField(max_length=80)),
                ('equipamento', models.CharField(choices=[('vtr', 'VIATURA'), ('moto', 'MOTO'), ('po', 'PO')], max_length=5)),
                ('data', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_saida', models.TimeField()),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_general.servidor')),
            ],
        ),
        migrations.CreateModel(
            name='Afinidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(auto_now=True)),
                ('matricula_rx', models.CharField(max_length=7)),
                ('cod_roteiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_general.roteiro')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_general.servidor')),
            ],
        ),
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(max_length=500)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('data_registro', models.DateField(auto_now=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_general.servidor')),
            ],
        ),
    ]
