# Generated by Django 4.1.4 on 2023-01-13 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('cod_local', models.AutoField(primary_key=True, serialize=False)),
                ('posto_base', models.CharField(max_length=30)),
                ('roteiro', models.TextField(max_length=300)),
                ('area', models.CharField(choices=[('a1', 'AREA 1'), ('a2', 'AREA 2'), ('a3', 'AREA 3'), ('a4', 'AREA 4'), ('a5', 'AREA 5'), ('a6', 'AREA 6'), ('a7', 'AREA 7'), ('a8', 'AREA 8'), ('a9', 'AREA 9'), ('a10', 'AREA 10'), ('a11', 'AREA 11')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('cod_operacao', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=500)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('matricula', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('grupo', models.CharField(choices=[('1', 'Grupo I'), ('2', 'Grupo II'), ('3', 'Grupo III'), ('4', 'Grupo IV')], max_length=1)),
                ('setor', models.CharField(choices=[('sefit', 'SEFIT'), ('sevop', 'SEVOP'), ('selve', 'SELVE'), ('areas', 'AREA'), ('coesp', 'COESP'), ('gasup', 'GASUP'), ('geren', 'GERENCIA')], max_length=5)),
                ('turno', models.CharField(choices=[('n', 'NOTURNO'), ('v', 'VESPERTINO'), ('m', 'MATUTINO')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitacao', models.TextField(max_length=500)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('data_registro', models.DateField(auto_now=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_general.servidor')),
            ],
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('cod_escala', models.AutoField(primary_key=True, serialize=False)),
                ('equipamento', models.CharField(choices=[('vtr', 'VIATURA'), ('moto', 'MOTO'), ('po', 'PO')], max_length=4)),
                ('data', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_saida', models.TimeField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_general.local')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_general.operacao')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_general.servidor')),
            ],
        ),
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('cod_afastamento', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=25)),
                ('descricao', models.TextField(max_length=500)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('data_registro', models.DateField(auto_now=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_general.servidor')),
            ],
        ),
    ]
