# Generated by Django 4.1.4 on 2023-01-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cod_pedido',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
