# Generated by Django 4.1.4 on 2023-01-11 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='cod_guarnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_general.guarnica'),
        ),
    ]
