# Generated by Django 4.1.4 on 2023-01-10 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_general', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servidor',
            old_name='x',
            new_name='parceiro',
        ),
        migrations.DeleteModel(
            name='Afinidade',
        ),
    ]
