# Generated by Django 4.1.4 on 2023-01-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_general', '0002_remove_pedido_id_pedido_cod_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='funcao',
            field=models.CharField(choices=[('vtr', 'COORDENADOR'), ('moto', 'SUPERVISOR'), ('po', 'GERENTE'), ('g', 'GUARNICAO'), ('adm', 'ADMINISTRACAO')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
