# Generated by Django 4.1.4 on 2023-01-10 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_general', '0002_rename_x_servidor_parceiro_delete_afinidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='parceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_general.servidor'),
        ),
    ]
